# -*- coding: utf-8 -*-

# Ui_Admin implementation generated from reading ui file 'Admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Admin(object):
    def setupUi(self, Ui_Admin):
        Ui_Admin.setObjectName("Ui_Admin")
        Ui_Admin.resize(800, 550)
        self.tab_0 = QtWidgets.QTabWidget(Ui_Admin)
        self.tab_0.setGeometry(QtCore.QRect(0, 0, 800, 550))
        self.tab_0.setObjectName("tab_0")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setEnabled(True)
        self.tab_1.setObjectName("tab_1")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit.setGeometry(QtCore.QRect(20, 40, 230, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 100, 230, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.tab_1)
        self.pushButton.setGeometry(QtCore.QRect(40, 230, 150, 50))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 300, 150, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_1)
        self.tableWidget.setGeometry(QtCore.QRect(279, 20, 502, 480))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(250)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.setHorizontalHeaderLabels(("Код специализации","Наименование специализации"))
        self.tab_0.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 70, 230, 30))
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(340, 70, 230, 30))
        self.lineEdit_4.setReadOnly(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 170, 150, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tab_0.addTab(self.tab_2, "")

        self.retranslateUi(Ui_Admin)
        self.tab_0.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Ui_Admin)

    def retranslateUi(self, Ui_Admin):
        _translate = QtCore.QCoreApplication.translate
        Ui_Admin.setWindowTitle(_translate("Ui_Admin", "Admin"))
        self.lineEdit.setPlaceholderText(_translate("Ui_Admin", "Код"))
        self.lineEdit_2.setPlaceholderText(_translate("Ui_Admin", "Название"))
        self.pushButton.setText(_translate("Ui_Admin", "Добавить"))
        self.pushButton_2.setText(_translate("Ui_Admin", "Удалить"))
        self.tab_0.setTabText(self.tab_0.indexOf(self.tab_1), _translate("Ui_Admin", "Список специальностей"))
        self.lineEdit_3.setPlaceholderText(_translate("Ui_Admin", "Новое количество мест"))
        self.lineEdit_4.setText(_translate("Ui_Admin", ""))
        self.pushButton_3.setText(_translate("Ui_Admin", "Изменить"))
        self.tab_0.setTabText(self.tab_0.indexOf(self.tab_2), _translate("Ui_Admin", "Количество мест"))