# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdmissonsOfficer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Admission_Officer(object):
    def setupUi(self, Admission_Officer):
        Admission_Officer.setObjectName("Admission_Officer")
        Admission_Officer.setEnabled(True)
        Admission_Officer.resize(600, 400)
        self.tabWidget = QtWidgets.QTabWidget(Admission_Officer)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 600, 400))
        self.tabWidget.setObjectName("tabWidget")
        self.Tab_1 = QtWidgets.QWidget()
        self.Tab_1.setObjectName("Tab_1")
        self.abit_ball = QtWidgets.QLineEdit(self.Tab_1)
        self.abit_ball.setGeometry(QtCore.QRect(60, 80, 475, 25))
        self.abit_ball.setClearButtonEnabled(True)
        self.abit_ball.setObjectName("abit_login_2")
        self.abit_password = QtWidgets.QLineEdit(self.Tab_1)
        self.abit_password.setGeometry(QtCore.QRect(60, 180, 475, 25))
        self.abit_password.setObjectName("abit_password")
        self.abit_FIO = QtWidgets.QLineEdit(self.Tab_1)
        self.abit_FIO.setGeometry(QtCore.QRect(60, 30, 475, 25))
        self.abit_FIO.setInputMask("")
        self.abit_FIO.setText("")
        self.abit_FIO.setClearButtonEnabled(True)
        self.abit_FIO.setObjectName("abit_FIO")
        self.abit_login = QtWidgets.QLineEdit(self.Tab_1)
        self.abit_login.setGeometry(QtCore.QRect(60, 130, 475, 25))
        self.abit_login.setClearButtonEnabled(True)
        self.abit_login.setObjectName("abit_login")
        self.abit_entry = QtWidgets.QPushButton(self.Tab_1)
        self.abit_entry.setGeometry(QtCore.QRect(100, 300, 150, 40))
        self.abit_entry.setObjectName("abit_entry")
        self.abit_del = QtWidgets.QPushButton(self.Tab_1)
        self.abit_del.setGeometry(QtCore.QRect(100, 250, 150, 40))
        self.abit_del.setObjectName("abit_del")
        self.abit_cancel = QtWidgets.QPushButton(self.Tab_1)
        self.abit_cancel.setGeometry(QtCore.QRect(340, 300, 150, 40))
        self.abit_cancel.setObjectName("abit_cancel")
        self.tabWidget.addTab(self.Tab_1, "")
        self.Tab2 = QtWidgets.QWidget()
        self.Tab2.setObjectName("Tab2")
        self.tableWidget = QtWidgets.QTableWidget(self.Tab2)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 600, 375))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(290)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(290)
        self.tabWidget.addTab(self.Tab2, "")

        self.retranslateUi(Admission_Officer)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Admission_Officer)

    def retranslateUi(self, Admission_Officer):
        _translate = QtCore.QCoreApplication.translate
        Admission_Officer.setWindowTitle(_translate("Admission_Officer", "Admissions Officer"))
        self.abit_ball.setPlaceholderText(_translate("Admission_Officer", "Суммарные баллы за ЕГЭ"))
        self.abit_password.setPlaceholderText(_translate("Admission_Officer", "Пароль"))
        self.abit_FIO.setPlaceholderText(_translate("Admission_Officer", "ФИО"))
        self.abit_login.setPlaceholderText(_translate("Admission_Officer", "Логин"))
        self.abit_entry.setText(_translate("Admission_Officer", "Зарегистрировать"))
        self.abit_del.setText(_translate("Admission_Officer", "Удалить"))
        self.abit_cancel.setText(_translate("Admission_Officer", "Отмена"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_1), _translate("Admission_Officer", "Регистрация абитуриента"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Admission_Officer", "Балл"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Admission_Officer", "ФИО"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab2), _translate("Admission_Officer", "Список абитуриентов"))