# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(550, 350)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.log_login = QtWidgets.QLineEdit(self.centralwidget)
        self.log_login.setGeometry(QtCore.QRect(80, 30, 400, 25))
        self.log_login.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.log_login.setInputMask("")
        self.log_login.setText("")
        self.log_login.setMaxLength(50)
        self.log_login.setClearButtonEnabled(True)
        self.log_login.setObjectName("log_login")
        self.log_entry = QtWidgets.QPushButton(self.centralwidget)
        self.log_entry.setGeometry(QtCore.QRect(200, 220, 120, 50))
        self.log_entry.setMouseTracking(True)
        self.log_entry.setObjectName("log_entry")
        self.log_password = QtWidgets.QLineEdit(self.centralwidget)
        self.log_password.setEnabled(True)
        self.log_password.setGeometry(QtCore.QRect(80, 80, 400, 25))
        self.log_password.setText("")
        self.log_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.log_password.setClearButtonEnabled(True)
        self.log_password.setObjectName("log_password")
        self.log_role = QtWidgets.QLineEdit(self.centralwidget)
        self.log_role.setGeometry(QtCore.QRect(80, 130, 400, 25))
        self.log_role.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.log_role.setInputMask("")
        self.log_role.setText("")
        self.log_role.setMaxLength(50)
        self.log_role.setClearButtonEnabled(True)
        self.log_role.setObjectName("log_role")
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Login"))
        self.log_login.setPlaceholderText(_translate("LoginWindow", "Логин"))
        self.log_entry.setText(_translate("LoginWindow", "Войти"))
        self.log_password.setPlaceholderText(_translate("LoginWindow", "Пароль"))
        self.log_role.setPlaceholderText(_translate("LoginWindow", "Роль"))