# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registration(object):
    def setupUi(self, Registration):
        Registration.setObjectName("Registration")
        Registration.resize(600, 400)
        self.reg_FIO = QtWidgets.QLineEdit(Registration)
        self.reg_FIO.setGeometry(QtCore.QRect(60, 30, 475, 25))
        self.reg_FIO.setInputMask("")
        self.reg_FIO.setText("")
        self.reg_FIO.setClearButtonEnabled(True)
        self.reg_FIO.setObjectName("reg_FIO")
        self.reg_works = QtWidgets.QComboBox(Registration)
        self.reg_works.setGeometry(QtCore.QRect(60, 80, 475, 25))
        self.reg_works.setObjectName("reg_works")
        self.reg_works.addItem("Администратор")
        self.reg_works.addItem("Секретарь")
        self.reg_works.addItem("Служащий приемной комиссии")
        self.reg_login = QtWidgets.QLineEdit(Registration)
        self.reg_login.setGeometry(QtCore.QRect(60, 130, 475, 25))
        self.reg_login.setClearButtonEnabled(True)
        self.reg_login.setObjectName("reg_login")
        self.reg_password = QtWidgets.QLineEdit(Registration)
        self.reg_password.setGeometry(QtCore.QRect(60, 180, 475, 25))
        self.reg_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.reg_password.setObjectName("reg_password")
        self.reg_registration = QtWidgets.QPushButton(Registration)
        self.reg_registration.setGeometry(QtCore.QRect(100, 300, 150, 40))
        self.reg_registration.setObjectName("reg_registration")
        self.reg_cancel = QtWidgets.QPushButton(Registration)
        self.reg_cancel.setGeometry(QtCore.QRect(340, 300, 150, 40))
        self.reg_cancel.setObjectName("reg_cancel")

        self.retranslateUi(Registration)
        QtCore.QMetaObject.connectSlotsByName(Registration)
    

    def retranslateUi(self, Registration):
        _translate = QtCore.QCoreApplication.translate
        Registration.setWindowTitle(_translate("Registration", "Registration"))
        self.reg_FIO.setPlaceholderText(_translate("Registration", "ФИО"))
        self.reg_login.setPlaceholderText(_translate("Registration", "Логин"))
        self.reg_password.setPlaceholderText(_translate("Registration", "Пароль"))
        self.reg_registration.setText(_translate("Registration", "Зарегистрироваться"))
        self.reg_cancel.setText(_translate("Registration", "Отмена"))